package com.matibabu.backend.encounter;

import com.matibabu.backend.domain.encounter.Encounter;
import com.matibabu.backend.domain.encounter.EncounterStatus;
import org.junit.jupiter.api.Test;

import java.time.Instant;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

class EncounterTest {

    /*
     * Verifies that a newly created Encounter starts in the ACTIVE state.
     *
     * An Encounter should have:
     * - an ID generated by the domain
     * - a patient ID
     * - a start time
     * - ACTIVE status
     * - no end time
     */
    @Test
    void shouldStartAsActive() {
        UUID patientId = UUID.randomUUID();
        Instant now = Instant.now();

        // Start a new encounter for the patient.
        Encounter encounter =
                Encounter.start(patientId, now);

        // The domain should generate an ID for the new encounter.
        assertNotNull(encounter.getId());

        // The supplied patient ID should be preserved.
        assertEquals(patientId, encounter.getPatientId());

        // The supplied start time should be preserved.
        assertEquals(now, encounter.getStartedAt());

        // A newly started encounter must always be ACTIVE.
        assertEquals(
                EncounterStatus.ACTIVE,
                encounter.getStatus()
        );

        // An active encounter has not ended yet.
        assertNull(encounter.getEndedAt());
    }


    /*
     * Verifies the normal discharge flow:
     *
     * ACTIVE → DISCHARGED
     *
     * Discharging an encounter should also record the time
     * at which the encounter ended.
     */
    @Test
    void shouldDischargeActiveEncounter() {
        UUID patientId = UUID.randomUUID();

        Instant startedAt =
                Instant.parse("2026-08-19T10:00:00Z");

        Instant dischargedAt =
                Instant.parse("2026-08-19T12:00:00Z");

        // Create an active encounter.
        Encounter encounter =
                Encounter.start(patientId, startedAt);

        // Perform the domain operation.
        encounter.discharge(dischargedAt);

        // The encounter should now be DISCHARGED.
        assertEquals(
                EncounterStatus.DISCHARGED,
                encounter.getStatus()
        );

        // The discharge time should be stored as the end time.
        assertEquals(
                dischargedAt,
                encounter.getEndedAt()
        );
    }


    /*
     * Verifies the cancellation flow:
     *
     * ACTIVE → CANCELLED
     *
     * Cancellation also ends the encounter, so endedAt
     * must be populated.
     */
    @Test
    void shouldCancelActiveEncounter() {
        UUID patientId = UUID.randomUUID();

        Instant startedAt =
                Instant.parse("2026-08-19T10:00:00Z");

        Instant cancelledAt =
                Instant.parse("2026-08-19T10:30:00Z");

        // Create an active encounter.
        Encounter encounter =
                Encounter.start(patientId, startedAt);

        // Cancel the encounter.
        encounter.cancel(cancelledAt);

        // Verify that the status changed correctly.
        assertEquals(
                EncounterStatus.CANCELLED,
                encounter.getStatus()
        );

        // Cancellation also records when the encounter ended.
        assertEquals(
                cancelledAt,
                encounter.getEndedAt()
        );
    }


    /*
     * An encounter that has already been discharged is in a
     * terminal state.
     *
     * Therefore:
     *
     * DISCHARGED → DISCHARGED
     *
     * should not be allowed.
     */
    @Test
    void shouldNotDischargeAlreadyDischargedEncounter() {
        UUID patientId = UUID.randomUUID();

        Instant startedAt =
                Instant.parse("2026-08-19T10:00:00Z");

        Instant dischargedAt =
                Instant.parse("2026-08-19T12:00:00Z");

        // Start the encounter.
        Encounter encounter =
                Encounter.start(patientId, startedAt);

        // Discharge it once.
        encounter.discharge(dischargedAt);

        // Attempting to discharge it again should fail.
        assertThrows(
                IllegalStateException.class,
                () -> encounter.discharge(dischargedAt)
        );
    }


    /*
     * Once an encounter has been discharged, it cannot be
     * cancelled.
     *
     * Valid:
     *
     * ACTIVE → DISCHARGED
     *
     * Invalid:
     *
     * DISCHARGED → CANCELLED
     */
    @Test
    void shouldNotCancelDischargedEncounter() {
        UUID patientId = UUID.randomUUID();

        Instant startedAt =
                Instant.parse("2026-08-19T10:00:00Z");

        Instant dischargedAt =
                Instant.parse("2026-08-19T12:00:00Z");

        // Create the encounter.
        Encounter encounter =
                Encounter.start(patientId, startedAt);

        // Move the encounter into its terminal DISCHARGED state.
        encounter.discharge(dischargedAt);

        // Cancellation after discharge must be rejected.
        assertThrows(
                IllegalStateException.class,
                () -> encounter.cancel(dischargedAt)
        );
    }


    /*
     * The end time can never occur before the start time.
     *
     * This protects the temporal consistency of the Encounter.
     */
    @Test
    void shouldNotAllowEndTimeBeforeStartTime() {
        UUID patientId = UUID.randomUUID();

        Instant startedAt =
                Instant.parse("2026-08-19T12:00:00Z");

        Instant invalidEndTime =
                Instant.parse("2026-08-19T10:00:00Z");

        // Create the encounter.
        Encounter encounter =
                Encounter.start(patientId, startedAt);

        // Attempt to discharge using a time before the encounter started.
        assertThrows(
                IllegalArgumentException.class,
                () -> encounter.discharge(invalidEndTime)
        );
    }
}